[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Isaac Freund <isaac.a.freund@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
pancurses = "0.16.1" # for total unnecessary day 13 graphics
rand = "0.7.2"
